# Lu par limine-mkinitcpio/limine-entry-tool.
KERNEL_CMDLINE[default]+=" quiet splash"
KERNEL_CMDLINE[default]+=" loglevel=3 systemd.show_status=false rd.systemd.show_status=false"
KERNEL_CMDLINE[default]+=" udev.log_level=3 rd.udev.log_level=3"
