# Thème Limine Kolossus.
# Modifier ce fichier puis relancer ./install-system-themes.sh.
# Les chemins des noyaux et les entrées de démarrage ne sont pas définis ici.

# Durée d’affichage du menu avant le démarrage de l’entrée par défaut.
quiet: no
timeout: 4

interface_branding: KOLOSSUS // SECURE STARTUP
interface_branding_color: faa968
interface_help_hidden: no
interface_help_color: f6dcac
interface_help_color_bright: faa968

wallpaper: boot():/limine/kolossus-wallpaper.jpg
wallpaper_style: stretched
backdrop: 00172e

term_font_scale: 1x1
term_font_spacing: 1
term_margin: 48
term_margin_gradient: 24
term_palette: 00172e;ff6b6b;7ed6a5;f6dcac;68aee8;c792ea;89ddff;d7e4f0
term_palette_bright: 254b6e;ff8f8f;a7e8c3;ffe9bd;8bc8f2;dda8ff;b6edff;ffffff
term_background: c000172e
term_foreground: f6dcac
term_background_bright: 254b6e
term_foreground_bright: ffffff
